fail_fast: true
repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    types: [python]
  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [python]
    exclude: ^migrations/
    args:
      - --config=.flake8
  - id: isort
    name: isort
    entry: isort
    language: system
    types: [python]
    args:
      - --profile=black
      - --resolve-all-configs
  - id: toml-sort
    name: toml-sort
    entry: toml-sort
    language: system
    files: pyproject.toml
    args:
      - --in-place
      - -a
